name: Hello world

on: 
    push:
        branches:
            - main

jobs:
    Hello:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World!
              run: |
                echo "Hello world"